version: "3.7"

services:
  api-server:
    build: .
    ports:
      - 9091:9091
    network_mode: "host"
    restart: always
  api-documentation:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - 8080:8080
