version: "3.1"

services:
  api-server:
    build: .
    ports:
      - 9091:9091
    network_mode: "host"
    restart: always
    deploy:
      restart_policy:
        condition: always
  api-documentation:
    build:
      context: .
      dockerfile: Dockerfile-api
      restart_policy:
        condition: always
    ports:
      - 8080:8080
